services:
  web:
    build: .
    image: xoxohorses/product-overview-api
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file: .env
    networks:
      - db_net

  db:
    image: postgres
    env_file: .env
    volumes:
      - /opt/homebrew/var/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      db_net:
        ipv4_address: 172.16.238.10

networks:
  db_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.10/16